#!/usr/bin/env bash
# ufw commands to block all incoming traffic except port 22 (SSH), port 80 (HTTP), and port 443 (HTTPS)

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable
