#!/bin/bash
# setting up firewall
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable

# Ensure input policy is DROP (filtered) not REJECT (closed)
sudo ufw default deny incoming
sudo iptables -P INPUT DROP
sudo ufw reload
