#!/usr/bin/env bash
# Installs Nginx on Ubuntu and adds X-Served-By set to this host's hostname (for load-balancer checks)
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

hn="$(hostname)"
conf=/etc/nginx/sites-available/default
tmp_file="$(mktemp)"
awk -v hn="$hn" '/server_name _;/ {
  print
  print "\tadd_header X-Served-By " hn ";"
  next
}
{ print }' "$conf" | sudo tee "$tmp_file" > /dev/null
sudo mv "$tmp_file" "$conf"

sudo service nginx restart
