#!/usr/bin/env bash
# Transfers a file to a remote user's home directory using scp
if [ "$#" -ge 4 ]
then
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
