#!/usr/bin/env bash
# Installs Nginx on Ubuntu, listens on port 80, serves a page containing Holberton School
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
